const allIngredients = ["salt", "pepper", "olive oil", "garlic", "onion", "butter", "sugar", "flour", "eggs", "milk",
"baking powder", "baking soda", "vanilla extract", "cinnamon", "nutmeg", "allspice", "cloves", 
"ginger", "cocoa powder", "honey", "brown sugar", "powdered sugar", "molasses", "maple syrup", 
"corn syrup", "yeast", "water", "cream", "sour cream", "heavy cream", "cream cheese", 
"cheddar cheese", "parmesan cheese", "mozzarella cheese", "goat cheese", "feta cheese", 
"blue cheese", "ricotta", "cottage cheese", "brie","chicken breast", "chicken thighs", 
"ground beef", "steak", "pork chops", "bacon", "ham", "salami", "prosciutto", "turkey", "duck", 
"lamb", "sausage", "hot dogs", "meatballs", "chorizo", "tilapia", "salmon", "tuna", "shrimp", 
"crab", "lobster", "clams", "mussels", "oysters", "anchovies", "sardines", "calamari", "scallops", 
"octopus", "rice", "brown rice", "wild rice", "quinoa", "couscous", "bulgur", "farro", "barley", 
"oats", "steel-cut oats", "instant oats", "cornmeal", "grits", "polenta", "bread crumbs", "panko", 
"pasta", "spaghetti", "penne", "macaroni", "fettuccine", "linguine", "lasagna noodles", 
"egg noodles", "ramen noodles", "udon noodles", "rice noodles", "glass noodles", "tortellini", 
"gnocchi", "potatoes", "sweet potatoes", "yams", "carrots", "celery", "bell pepper", "jalapeño", 
"habanero", "banana peppers", "chili peppers", "cabbage", "spinach", "kale", "lettuce", "romaine", 
"arugula", "chard", "collard greens", "broccoli", "cauliflower", "brussels sprouts", "green beans", 
"snap peas", "peas", "zucchini", "yellow squash", "butternut squash", "acorn squash", "pumpkin", 
"eggplant", "cucumber", "tomatoes", "cherry tomatoes", "sun-dried tomatoes", "avocado", "beets", 
"radish", "turnip", "parsnip", "leeks", "scallions", "shallots", "mushrooms", "portobello mushrooms", 
"shiitake mushrooms", "cremini mushrooms", "white mushrooms", "truffle", "artichoke", "okra", "corn", 
"asparagus", "bok choy", "watercress", "seaweed", "nori", "kimchi", "sauerkraut", "pickles", "olives",
"green olives", "black olives", "capers", "sunflower seeds", "pumpkin seeds", "chia seeds", "flax seeds", 
"sesame seeds", "poppy seeds", "almonds", "walnuts", "pecans", "cashews", "peanuts", "hazelnuts", 
"macadamia nuts", "pine nuts", "brazil nuts", "coconut", "shredded coconut", "coconut milk", 
"coconut cream", "almond milk", "soy milk", "oat milk", "rice milk", "cashew milk", "hemp milk", 
"tofu", "tempeh", "seitan", "lentils", "chickpeas", "black beans", "kidney beans", "pinto beans", 
"white beans", "navy beans", "cannellini beans", "refried beans", "edamame", "green lentils", 
"red lentils", "yellow lentils", "split peas", "miso paste", "soy sauce", "tamari", "fish sauce", 
"hoisin sauce","teriyaki sauce", "sriracha", "chili paste", "gochujang", "harissa", "tahini", 
"vinegar", "apple cider vinegar", "white vinegar", "red wine vinegar", "balsamic vinegar", 
"rice vinegar", "malt vinegar", "mustard", "dijon mustard", "yellow mustard", "whole grain mustard", 
"mayonnaise", "ketchup", "barbecue sauce", "buffalo sauce", "ranch", "caesar dressing", 
"italian dressing", "vinaigrette", "hot sauce", "tabasco", "worcestershire sauce", "cornstarch", 
"arrowroot powder", "tapioca starch", "xanthan gum", "gelatin", "agar agar", "instant pudding mix", 
"jello mix", "lemon juice", "lime juice", "orange juice", "grapefruit juice", "apple juice", 
"cranberry juice", "pomegranate juice", "pineapple juice", "tomato juice", "clam juice", 
"beef broth", "chicken broth", "vegetable broth", "bone broth", "bouillon cubes", "stock", "wine", 
"white wine", "red wine", "cooking sherry", "beer", "cider", "whiskey", "rum", "vodka", "brandy", 
"liqueur", "espresso", "coffee", "instant coffee", "tea", "black tea", "green tea", "herbal tea",
"matcha", "cocoa nibs", "dark chocolate", "milk chocolate", "white chocolate", "chocolate chips", 
"caramel", "marshmallows", "graham crackers", "graham cracker crumbs", "pretzels", "crackers", 
"tortilla chips", "potato chips", "bread", "baguette", "sourdough", "rye bread", "pita", "naan",
"flatbread", "tortillas", "whole wheat bread", "english muffin", "croissant", "biscuits", 
"pancake mix", "waffle mix", "cornbread", "muffin mix", "cake mix", "brownie mix", "frosting", 
"icing", "sprinkles", "jelly", "jam", "preserves", "peanut butter", "almond butter", 
"hazelnut spread", "apple sauce", "fruit cocktail", "fruit preserves", "banana", "apple", 
"pear", "peach", "plum", "grapes","strawberries", "blueberries", "raspberries", "blackberries", 
"cranberries", "cherries", "mango", "pineapple", "kiwi", "papaya","cantaloupe", "honeydew", 
"watermelon", "fig", "date", "raisin", "currants", "apricots", "prunes", "lychee", 
"passion fruit", "dragon fruit", "star fruit", "guava", "persimmon", "tamarind", "plantain", 
"lemon", "lime", "orange", "grapefruit", "herbs", "basil", "oregano", "thyme", "rosemary", 
"parsley", "cilantro", "dill", "mint", "chives", "bay leaves", "sage", "tarragon", 
"marjoram", "lavender", "lemongrass", "curry leaves", "turmeric", "paprika", "smoked paprika", 
"cayenne pepper", "chili powder", "garam masala", "cumin", "coriander", "cardamom", 
"fennel seeds", "mustard seeds", "caraway seeds", "anise", "saffron", "sumac", "za’atar", 
"old bay seasoning", "italian seasoning", "herbes de provence", "everything bagel seasoning", 
"nutritional yeast", "msg", "toast", "pancakes", "waffles", "oatmeal", "cereal", "granola", 
"yogurt", "smoothie", "protein shake", "milkshake", "tomato sauce", "chicken", "beef", "beans", 
"hummus", "prok", "noodels", "popcorn", "fruit", "nuts", "protein bar", "boiled eggs", "seeds", 
"greek yougurt"
];

export default allIngredients;